import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>LAMBORGHINI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>Inizia il tuo percorso dalla compravendita della&nbsp;
            <code className={styles.code}>LAMBORGHINI</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
               {" "}
              <Image
                src="/image/logo.png"
                alt="Vercel Logo"
                width={250}
                height={125}
                priority
              />
            </a>
          </div>
        </div>
      

        <div className={styles.center}>
          <Image
            src="/image/lambooo.png"
            alt="Next.js Logo"
            width={1000}
            height={500}
            priority
          />
        </div>
        <div className={styles.title1}>
        <h1>LA NOSTRA STORIA</h1>
        </div>
        <br></br>
        <div className={styles.title2}>
        <p>Con l'annessione del Veneto all'Italia, l'amministrazione comunale di San Donà cambiò assetto: il Consiglio comunale divenne l'organo principale e il Sindaco, di nomina regia, era scelto tra i consiglieri. L'affiancava una Giunta di Assessori. Le normative sull'elettorato si estesero progressivamente: nel 1882 furono ammessi al voto politico i cittadini maggiorenni con istruzione obbligatoria o un censo di 19,80 lire. Successivamente, nel 1915, l'elettorato amministrativo comunale fu esteso a tutti i cittadini italiani di 21 anni residenti o contribuenti nel comune, purché senza cause di esclusione.</p>
          </div>
<br></br>
        <div className={styles.grid}>
          <a
            href="configurator/configurators"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
            CONFIGURATOR <span>-&gt;</span>
            </h2>
            <p>
            CREA LA TUA REVUELTO&nbsp;           
            </p>
          </a>

          <a
            href="concessionari/concessionario"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
            CONCESSIONARI<span>-&gt;</span>
            </h2>
            <p>
            TROVA UN CONCESSIONARIO NEL TUO PAESE&nbsp;
            </p>
          </a>

          <a
            href="revuelto/rev"
            className={styles.card}
            target="_black"
            rel="noopener noreferrer"
          >
            <h2>
            REVUELTO <span>-&gt;</span>
            </h2>
            <p>
            FROM NOW ON&nbsp;
            </p>
          </a>

          <a
            href="notizie/not"
            className={styles.card}
            target="_black"
            rel="noopener noreferrer"
          >
            <h2>
            NOTIZIE<span>-&gt;</span>
            </h2>
            <p>
            LAMBORGHINI WORLD&nbsp;
            </p>
          </a>
          <a
            href="store/stoore"
            className={styles.cards}
            target="_black"
            rel="noopener noreferrer"
          >
            <h2>
              STORE <span>-&gt;</span>
            </h2>
            <p>
              &nbsp;
            </p>
          </a>
        
          
          
        </div>
        <h1>I NOSTRI SPONSOR</h1>
        <br></br><br></br><br></br>
        <div className={styles.center}>
          <Image
            src="/image/immagineso.png"
            alt="Next.js Logo"
            width={2000}
            height={500}
            priority
          />
        </div>
            
          
      </main>
    </>
  );
}